### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by dettervt** [kp394/WinkGUI#1]
GUI: Basic one that fills out the GUIPacket class to be passed along the network
Communication: Network abstraction, this one is surprisingly easy
Server with DB hooks: This is the one I've been chipping away on, its rather buggy at the moment, working on it tonight and tomorrow to have it fine
CLI: I'll whip up a quick command line interface to use while the GUI is under development

Let me know if you want to work together on any of these.

**Comment by kp394** [comment]
GUI: I added the functionality to the GUI so it will create a GUIPacket object and pass it along the network when the submit button is pressed. 

I would be happy to work with you on the rest of the stuff that needs to get done, but you might have to be more patient with me on those because I don't have as much experience with them.
